name: 'Setup Node Environment'
description: 'Setup Node, cache and clean install'

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Cache Playwright Binaries
      id: cache-playwright
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash

    - name: Install playwright browsers
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
      shell: bash

    - name: Install system dependencies for WebKit
      # Some WebKit dependencies seem to lay outside the cache and will need to be installed separately
      if: steps.cache-playwright.outputs.cache-hit == 'true'
      run: npx playwright install-deps webkit
      shell: bash
