name: Test
# on: [push, pull_request, workflow_dispatch]
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-env

      - name: Run unit tests
        run: npm run-script test:unit

      - name: Run visual regression tests on PR
        if: github.event_name == 'pull_request'
        run: npm run-script test:visual
